# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8434e1eb877f13ccd6559598b06c3aee"
name = "order-alerts"
application_url = "https://iso-ought-document-proceeds.trycloudflare.com"
embedded = true
handle = "order-alerts-7"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders"

[auth]
redirect_urls = ["https://iso-ought-document-proceeds.trycloudflare.com/auth/callback", "https://iso-ought-document-proceeds.trycloudflare.com/auth/shopify/callback", "https://iso-ought-document-proceeds.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
